# Generated by Django 5.2.14 on 2026-05-20 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_de_recuperacao', models.IntegerField(choices=[(4, 'Excelente - me sinto muito bem'), (3, 'Boa - estou melhorando'), (2, 'Regular - ainda tenho dificuldades'), (1, 'Ruim - não estou melhorando')], default=1, max_length=1)),
                ('nivel_de_dor', models.PositiveIntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(10))),
                ('retorno_atividades', models.IntegerField(choices=[(4, 'Sim, completamente'), (3, 'Parcialmente'), (2, 'Ainda não consigo'), (1, 'Não se aplica')], default=1)),
                ('satisfacao_resultado', models.PositiveIntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(10))),
            ],
        ),
    ]
